<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <RootNamespace>transmit_gcode</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\core\core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="System.IO.Ports" Version="7.0.0" />
    </ItemGroup>

</Project>
